---
title: "sharereward_figures"
author: "Jen Yang"
date: "2025-10-29, last modified 2025-10-30"
output:
  word_document:
    toc: true
    toc_depth: '6'
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    hightlight: zenburn
    toc_depth: 6
---

```{r clean, include=FALSE}
# clean environment
rm(list = ls())
```

# Load libraries
```{r libraries, message=FALSE, warning=TRUE, include=FALSE}
library(car)
library(plyr)
library(foreign)
library(pscl)
library(boot)
library(MASS)
library(robust)
library(sfsmisc)
library(ggplot2)
library(reshape2)
library(ppcor)
library(ggrepel)
library(Hmisc)
library(tidyverse)
library(magrittr)
library(sandwich)
library(ggpubr)
library(interactions)
library(knitr)
library(twowaytests)
library(ggfortify)
library(interactions)
library(broom)
library(patchwork)
library(robustbase)
library(lmtest)
library(modelr)
library(Rmisc)
library(cowplot)
library(readr)
library(PupillometryR)
library(ggpp)
library(estimatr)
library(skedastic)
library(ggpubr)
library(lubridate)
library(readxl)
library(gridExtra)
library(scales)
library(rstudioapi)
library(jsonlite)
library(rjson)
library(readr)
library(rstan)
library(easystats)
library(patchwork)
library(brms)
```

# define dir and load data
```{r}
# gitrepo_path = here() # find repo path
gitrepo_path = "/Users/momocco/Documents/GitHub/rf1-sra-sharedreward/blobs_jen"

code_dir = paste(gitrepo_path, "code", sep = "/")
data_dir = paste(gitrepo_path, "data", sep = "/")
figure_dir = paste(gitrepo_path, "figure", sep = "/")
```

# Cooper's code, for model checking
```{r}
# ppi_VS-VS_c14_age-effect

# from Cooper
## model3 <- lm(`ppi_VS.VS_c14_2mm_model.Fwin.Floss_Swin.Sloss_type.ppi_seed.VS_cope.14_cname.rew.pun_F.S` ~ age_demeaned + avg_tsnr_demeaned + avg_fdmean_demeaned + flip_demeaned + study_demeaned + Fwin_minus_Floss_minus_Swin_minus_Sloss_z_demeaned + age_x_Fwin_minus_Floss_minus_Swin_minus_Sloss_z_demeaned, data = df, weights = `weights_var_ppi_VS-VS_c14_2mm_model.Fwin.Floss_Swin.Sloss_type.ppi_seed.VS_cope.14_cname.rew.pun_F.S`)

# inventry

## DV = `ppi_VS.VS_c14_2mm_model.Fwin.Floss_Swin.Sloss_type.ppi_seed.VS_cope.14_cname.rew.pun_F.S`

## IV focal = age_demeaned

## IV control = 
## avg_tsnr_demeaned
## avg_fdmean_demeaned
## flip_demeaned
## study_demeaned
## Fwin_minus_Floss_minus_Swin_minus_Sloss_z_demeaned
# age_x_Fwin_minus_Floss_minus_Swin_minus_Sloss_z_demeaned

## weights = `weights_var_ppi_VS-VS_c14_2mm_model.Fwin.Floss_Swin.Sloss_type.ppi_seed.VS_cope.14_cname.rew.pun_F.S`)
```

# prepare data
```{r}
csv_name = "jen-SRaging.csv"
raw_df = read.csv(paste(data_dir, csv_name, sep = "/"),
                  header = T)

plot_df = raw_df %>% 
  mutate(weights = 1/`var_ppi_VS.VS_c14_2mm_model.Fwin.Floss_Swin.Sloss_type.ppi_seed.VS_cope.14_cname.rew.pun_F.S`) %>% 
  rename(
    DV = `ppi_VS.VS_c14_2mm_model.Fwin.Floss_Swin.Sloss_type.ppi_seed.VS_cope.14_cname.rew.pun_F.S`,
    IV_focal = age_demeaned,
    ctrl_tsnr = avg_tsnr_demeaned,
    ctrl_fdmean = avg_fdmean_demeaned,
    ctrl_study = study_demeaned,
    ctrl_flip = flip_demeaned,
    ctrl_z_1 = Fwin_minus_Floss_minus_Swin_minus_Sloss_z_demeaned,
    ctrl_z_2 = age_x_Fwin_minus_Floss_minus_Swin_minus_Sloss_z_demeaned) %>% 
  mutate(DV_norm = DV/sd(DV),
         IV_focal_norm = IV_focal/sd(IV_focal)) %>% 
  select(DV, DV_norm,
         IV_focal, IV_focal_norm,
         ctrl_tsnr, ctrl_fdmean, ctrl_study, ctrl_flip, ctrl_z_1, ctrl_z_2, 
         weights) 
```

# stats check
```{r}
# withOUT weight
VS_VS_m_r_ols = lm(DV ~ IV_focal +
                     ctrl_tsnr + ctrl_fdmean + ctrl_study + ctrl_flip + ctrl_z_1 + ctrl_z_2,
                   data = plot_df)
summary(VS_VS_m_r_ols)

full_summary = summary(VS_VS_m_r_ols)

# WITH weight
## full model
m_wls = lm(DV ~ 
             IV_focal +
             ctrl_tsnr + ctrl_fdmean + ctrl_study + ctrl_flip + ctrl_z_1 + ctrl_z_2,
           data = plot_df, weights = plot_df$weights)
summary(m_wls)

full_summary = summary(m_wls)
r2_full_adj = full_summary$adj.r.squared
r2_full = full_summary$r.squared

## reduced model
m_wls_null = lm(DV ~
                  ctrl_tsnr + ctrl_fdmean + ctrl_study + ctrl_flip + ctrl_z_1 + ctrl_z_2,
                data = plot_df, weights = plot_df$weights)
# summary(m_wls_null)

reduced_summary = summary(m_wls_null)
r2_reduced_adj = reduced_summary$adj.r.squared
r2_reduced = reduced_summary$r.squared

# Cohen's f squared
(r2_full_adj-r2_reduced_adj)/(1-r2_full_adj)

(r2_full-r2_reduced)/(1-r2_full)
```

# figure, with controls
## residual data prep
```{r}
# Residuals of Y, controlling for A (weighted)
resid_DV_on_ctrl <- 
  resid(lm(DV ~ 
             ctrl_tsnr + ctrl_fdmean + ctrl_study + ctrl_flip + ctrl_z_1 + ctrl_z_2,
           data = plot_df, weights = plot_df$weights))

# Residuals of X, controlling for A (weighted)
resid_IV_on_ctrl <- 
  resid(lm(IV_focal ~
             ctrl_tsnr + ctrl_fdmean + ctrl_study + ctrl_flip + ctrl_z_1 + ctrl_z_2,
           data = plot_df, weights = plot_df$weights))

partial_data <- data.frame(
  DV_adj = resid_DV_on_ctrl,
  IV_adj = resid_IV_on_ctrl,
  weights = plot_df$weights)
```

## coef and se verification
```{r}
m_wls = lm(DV ~ 
             IV_focal +
             ctrl_tsnr + ctrl_fdmean + ctrl_study + ctrl_flip + ctrl_z_1 + ctrl_z_2,
           data = plot_df, weights = plot_df$weights)

partial_wls <- lm(DV_adj ~ IV_adj + 0, 
                  data = partial_data, weights = partial_data$weights)
summary(partial_wls)
partial_wls_tidy <- tidy(partial_wls)
coef_partial_wls_tidy <- partial_wls_tidy[partial_wls_tidy$term == "IV_adj", ]

m_wls_tidy <- tidy(m_wls)
coef_m_wls_tidy <- m_wls_tidy[m_wls_tidy$term == "IV_focal", ]

print(coef_partial_wls_tidy)
print(coef_m_wls_tidy)

```

## prepare line and se data
```{r}
line_df <- data.frame(IV_adj = seq(min(partial_data$IV_adj), max(partial_data$IV_adj), length.out = 100))

line_DV_pred <- predict(partial_wls, newdata = line_grid, interval = "confidence")
line_df <- cbind(line_grid, as.data.frame(line_DV_pred))
```

# figure param setup
```{r}
axis_title = 12
axis_ticks = 10
axis_text = 12
axis_label = 12

legend_all = 12

annotate_text = 4
axis_line_width = 1/1.5
fit_line_width = 2
zero_line_width = 0.6
path_line_width = 0.5

data_point_alpha = 0.5
data_point_size = 1
path_line_alpha = 0.6

mean_point_size = 3

line_width = 1
point_size = 3

summary_point_alpha = 1
summary_point_size = 3

annotate_text = 4

smooth_alpha = 0.3

w = 3.4
h = 3.4

# color_Stranger = "#ee964b"
# color_Friend = "#118ab2"
# 
# color_Trust = "#2a9d8f"
# color_NotTrust = "#d8315b"
# 
# color_age = "#0b6e4f"
# color_In_Im = "#592e83"
```

# plot
```{r}
wls_p = 
  ggplot() +
  # original data points with weights represented by size
  geom_point(data = partial_data, 
             aes(x = IV_adj, y = DV_adj, 
                 alpha = weights),
             color = "darkblue") +
  # se using simulated data
  geom_ribbon(data = line_df, 
              aes(x = IV_adj, 
                  ymin = lwr, 
                  ymax = upr), 
              fill = "darkred", 
              alpha = 0.4) +
  # line with partial coef
  geom_line(data = line_df, 
            aes(x = IV_adj, y = fit), 
            color = "darkred", linewidth = 1.1) +
  labs(x = "age (demeaned)", 
       y = "brain, partial residual",
       color = NULL,
       fill = NULL) +
  coord_cartesian(ylim = c(-10, 10)) +
  theme(axis.line = 
          element_line(linewidth = 1, 
                       colour = "black", 
                       linetype=1),
        axis.text.x = element_text(size = axis_text), 
        axis.text.y = element_text(size = axis_text), 
        axis.title.x = element_text(size = axis_title, face="bold"), 
        axis.title.y = element_text(size = axis_title, face="bold"),
        panel.grid.minor = element_blank()
        # legend.position = c(0.8, 0.8)
  )
wls_p
```





# end of code

